### ISSUE TITLE
DataBase Problem

### ISSUE THREAD

**Issue by Kenan179** [OpenBMP/openbmp#61]
Hi,

I've installed the container for UI and for the AIO, and I enable BGP monitoring on our router.
I can see all BGP update on the tcpdump and in the rib and the collectors, but nothing is showing under routers or v_routes.
I'm not sure what I am missing. can anyone assit?

Kenan

**Comment by bugtoo** [comment]
Hi @Kenan179, try removing any spread configuration from your router initial-refresh-delay (i.e. issue only initial-refresh-delay 60), then with the openbmp server up try a shutdown and commit of the bmp server entry on the router, wait a few seconds and issue a no shutdown: the routers should appear in the db. I don't know the reason yet, but if you start the openbmp server when the routers are already configured, when they connect to the bmp server, openbmp will not popoluate the routers and peers table. Perhaps @TimEvens can give some input?

**Comment by Kenan179** [comment]
@bugtoo You are right, I did that and now everything is working. 
Thanks.

**Comment by TimEvens** [comment]
@Kenan179, @bugtoo, 

This issue was caused by a default in the mysql consumer config file that configured the consumer to use latest offset instead of earliest.   This has now been fixed in the latest build.   

After a fresh install, Kafka/zookeeper isn’t tracking the consumer yet.  When a router connects and sends peer ups sooner than the startup delay, it resulted in the consumer skipping those messages.  The change back to “earliest”resovles this.    The config you used works because it delayed the init and peer ups.  You shouldn’t have to do that. ;)
